"""Crea en Oracle FCME_USER:
 1) Tabla CDC_INBOX_MODULE_CONFIG
 2) Tabla CDC_INBOX_ERRORS
 3) SEQUENCE para IDs
 4) SP USP_INBOX_PARTICIPE (piloto: actualizacionAfiliadoType)
 5) Trigger TRG_PROCESS_CDC_INBOX AFTER INSERT
 6) Pobla CDC_INBOX_MODULE_CONFIG
 7) Fuerza reproceso de los eventos pending
"""
import oracledb
orcl = oracledb.connect(user="fcme_user", password="FcmeUser2025!",
                        dsn="10.35.3.223:31521/XEPDB1")
c = orcl.cursor()

def run(sql, silent_errors=None):
    try:
        c.execute(sql)
        print("  ok")
    except Exception as e:
        msg = str(e)
        if silent_errors and any(s in msg for s in silent_errors):
            print(f"  skip ({msg.split(chr(10))[0][:80]})")
        else:
            print(f"  ERR: {msg[:300]}")
            raise

# 1) Tabla config
print("[1] CDC_INBOX_MODULE_CONFIG")
run("""
CREATE TABLE CDC_INBOX_MODULE_CONFIG (
    AGGREGATE_TYPE VARCHAR2(200) NOT NULL,
    SP_NAME        VARCHAR2(300) NOT NULL,
    ACTIVE         NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_CDC_INBOX_MODULE_CONFIG PRIMARY KEY (AGGREGATE_TYPE)
)""", silent_errors=["ORA-00955"])

# 2) Tabla errors
print("[2] CDC_INBOX_ERRORS")
run("""
CREATE TABLE CDC_INBOX_ERRORS (
    ID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    INBOX_ID       NUMBER NOT NULL,
    AGGREGATE_TYPE VARCHAR2(200),
    EVENT_TYPE     VARCHAR2(200),
    ERROR_MESSAGE  VARCHAR2(4000),
    ERROR_DATE     TIMESTAMP DEFAULT SYSTIMESTAMP
)""", silent_errors=["ORA-00955"])

# 3) SP procesador
print("[3] USP_INBOX_PARTICIPE (piloto actualizacionAfiliadoType)")
run("""
CREATE OR REPLACE PROCEDURE USP_INBOX_PARTICIPE(
    p_aggregate_type IN VARCHAR2,
    p_event_type     IN VARCHAR2,
    p_payload        IN CLOB
) AS
    v_cedu VARCHAR2(100);
    v_count NUMBER;
BEGIN
    IF p_aggregate_type = 'actualizacionAfiliadoType' THEN
        v_cedu := JSON_VALUE(p_payload, '$.ci_cedu');
        IF v_cedu IS NULL THEN RETURN; END IF;

        IF p_event_type IN ('DELETE','DELETED') THEN
            DELETE FROM ACTUALIZACION_AFILIADO_TYPE WHERE CODIGO_CEDU = v_cedu;
            RETURN;
        END IF;

        -- Upsert (no hay PK fisica, dedup por CODIGO_CEDU)
        SELECT COUNT(*) INTO v_count FROM ACTUALIZACION_AFILIADO_TYPE WHERE CODIGO_CEDU = v_cedu;
        IF v_count = 0 THEN
            INSERT INTO ACTUALIZACION_AFILIADO_TYPE (
                CODIGO_CEDU, CODIGO_PROV, CODIGO_CANT, CODIGO_PARR,
                DESCRIPCION_CALL_PRIM, NUMERO_CALL_PRIM, DESCRIPCION_CALL_SECU, NUMERO_CALL_SECU,
                NUMERO_MANZ, NUMERO_VILL, DESCRIPCION_CDLA,
                TEXTO_TELF_CONVENIO, TEXTO_TELF_CELU,
                TIPO_OPERACION, DESCRIPCION_REFERENCIA_VIVI, TEXTO_MAIL, NOMBRE_CONTABLE_ADIC,
                TEXTO_TELF_CON1, TEXTO_TELF_CON2, TIPO_RELA,
                CODIGO_PROV_INST, CODIGO_TIPO, CODIGO_INST, CODIGO_CARG, CODIGO_NIVE, CODIGO_CATE,
                TIPO_CONTABLE, TIPO_JORN,
                CODIGO_PROV_OBSQ, CODIGO_ZONA_OBSQ,
                INDICADOR_RENO_CREDITO, INDICADOR_ACCI,
                FECHA_INGRESO, FECHA_MODIFICACION, FECHA_ULTM_ENVI,
                INDICADOR_IMPR_DOCUMENTO, FECHA_IMPR_DOCUMENTO,
                INDICADOR_COBRANZA_PRES, INDICADOR_VALD_CELU, INDICADOR_VALD_MAIL,
                CODIGO_AMI, ESTADO_ENTR_OBSQ, FECHA_ENTR_OBSQ, FECHA_VERI_DATO,
                INDICADOR_IMPR_DOCUMENTO_CRED, FECHA_IMPR_DOCUMENTO_CREDITO,
                NOMBRE_INST, CODIGO_CANT_INST, CODIGO_PARR_INST
            ) VALUES (
                v_cedu,
                JSON_VALUE(p_payload,'$.co_prov'),  JSON_VALUE(p_payload,'$.co_cant'), JSON_VALUE(p_payload,'$.co_parr'),
                JSON_VALUE(p_payload,'$.ds_call_prim'), JSON_VALUE(p_payload,'$.nu_call_prim'),
                JSON_VALUE(p_payload,'$.ds_call_secu'), JSON_VALUE(p_payload,'$.nu_call_secu'),
                JSON_VALUE(p_payload,'$.nu_manz'), JSON_VALUE(p_payload,'$.nu_vill'), JSON_VALUE(p_payload,'$.ds_cdla'),
                JSON_VALUE(p_payload,'$.tx_telf_conv'), JSON_VALUE(p_payload,'$.tx_telf_celu'),
                JSON_VALUE(p_payload,'$.ti_oper'), JSON_VALUE(p_payload,'$.ds_refe_vivi'),
                JSON_VALUE(p_payload,'$.tx_mail'), JSON_VALUE(p_payload,'$.no_cont_adic'),
                JSON_VALUE(p_payload,'$.tx_telf_con1'), JSON_VALUE(p_payload,'$.tx_telf_con2'), JSON_VALUE(p_payload,'$.ti_rela'),
                JSON_VALUE(p_payload,'$.co_prov_inst'), JSON_VALUE(p_payload,'$.co_tipo'), JSON_VALUE(p_payload,'$.co_inst'),
                JSON_VALUE(p_payload,'$.co_carg'), JSON_VALUE(p_payload,'$.co_nive'), JSON_VALUE(p_payload,'$.co_cate'),
                JSON_VALUE(p_payload,'$.ti_contable'), JSON_VALUE(p_payload,'$.ti_jorn'),
                JSON_VALUE(p_payload,'$.co_prov_obsq'), JSON_VALUE(p_payload,'$.co_zona_obsq'),
                JSON_VALUE(p_payload,'$.in_reno_credito'), JSON_VALUE(p_payload,'$.in_acci'),
                JSON_VALUE(p_payload,'$.fx_ingr'), JSON_VALUE(p_payload,'$.fx_modi'), JSON_VALUE(p_payload,'$.fx_ultm_envi'),
                JSON_VALUE(p_payload,'$.in_impr_documento'), JSON_VALUE(p_payload,'$.fx_impr_documento'),
                JSON_VALUE(p_payload,'$.in_cobranza_pres'), JSON_VALUE(p_payload,'$.in_vald_celu'), JSON_VALUE(p_payload,'$.in_vald_mail'),
                JSON_VALUE(p_payload,'$.co_ami'), JSON_VALUE(p_payload,'$.estado_entr_obsq'),
                JSON_VALUE(p_payload,'$.fx_entr_obsq'), JSON_VALUE(p_payload,'$.fx_veri_dato'),
                JSON_VALUE(p_payload,'$.in_impr_documento_cred'), JSON_VALUE(p_payload,'$.fx_impr_documento_credito'),
                JSON_VALUE(p_payload,'$.no_inst'), JSON_VALUE(p_payload,'$.co_cant_inst'), JSON_VALUE(p_payload,'$.co_parr_inst')
            );
        ELSE
            UPDATE ACTUALIZACION_AFILIADO_TYPE SET
                CODIGO_PROV = JSON_VALUE(p_payload,'$.co_prov'),
                CODIGO_CANT = JSON_VALUE(p_payload,'$.co_cant'),
                CODIGO_PARR = JSON_VALUE(p_payload,'$.co_parr'),
                DESCRIPCION_CALL_PRIM = JSON_VALUE(p_payload,'$.ds_call_prim'),
                NUMERO_CALL_PRIM = JSON_VALUE(p_payload,'$.nu_call_prim'),
                DESCRIPCION_CALL_SECU = JSON_VALUE(p_payload,'$.ds_call_secu'),
                NUMERO_CALL_SECU = JSON_VALUE(p_payload,'$.nu_call_secu'),
                NUMERO_MANZ = JSON_VALUE(p_payload,'$.nu_manz'),
                NUMERO_VILL = JSON_VALUE(p_payload,'$.nu_vill'),
                DESCRIPCION_CDLA = JSON_VALUE(p_payload,'$.ds_cdla'),
                TEXTO_TELF_CONVENIO = JSON_VALUE(p_payload,'$.tx_telf_conv'),
                TEXTO_TELF_CELU = JSON_VALUE(p_payload,'$.tx_telf_celu'),
                TEXTO_MAIL = JSON_VALUE(p_payload,'$.tx_mail'),
                FECHA_MODIFICACION = JSON_VALUE(p_payload,'$.fx_modi')
            WHERE CODIGO_CEDU = v_cedu;
        END IF;

    -- Types no implementados aun: naturalTrabajoType, personaTelefonosType
    -- Estos quedaran con processed=0 pero sin error (se implementan cuando se defina el mapeo)
    ELSE
        NULL;
    END IF;
END;
""")

# 4) Trigger AFTER INSERT
print("[4] TRG_PROCESS_CDC_INBOX")
run("""
CREATE OR REPLACE TRIGGER TRG_PROCESS_CDC_INBOX
AFTER INSERT ON CDC_INBOX
FOR EACH ROW
DECLARE
    v_sp VARCHAR2(300);
    v_plsql VARCHAR2(2000);
BEGIN
    SELECT SP_NAME INTO v_sp FROM CDC_INBOX_MODULE_CONFIG
    WHERE AGGREGATE_TYPE = :NEW.AGGREGATE_TYPE AND ACTIVE = 1;

    v_plsql := 'BEGIN '||v_sp||'(:1, :2, :3); END;';
    EXECUTE IMMEDIATE v_plsql USING :NEW.AGGREGATE_TYPE, :NEW.EVENT_TYPE, :NEW.PAYLOAD;

    UPDATE CDC_INBOX
    SET PROCESSED = 1, PROCESSED_AT = SYSTIMESTAMP
    WHERE ID = :NEW.ID;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        -- aggregate_type no mapeado; no procesar pero no marcar error
        NULL;
    WHEN OTHERS THEN
        INSERT INTO CDC_INBOX_ERRORS (INBOX_ID, AGGREGATE_TYPE, EVENT_TYPE, ERROR_MESSAGE)
        VALUES (:NEW.ID, :NEW.AGGREGATE_TYPE, :NEW.EVENT_TYPE, SUBSTR(SQLERRM,1,4000));
END;
""")

# 5) Poblar CDC_INBOX_MODULE_CONFIG
print("[5] Poblar CDC_INBOX_MODULE_CONFIG")
c.execute("DELETE FROM CDC_INBOX_MODULE_CONFIG WHERE AGGREGATE_TYPE = 'actualizacionAfiliadoType'")
c.execute("""
    INSERT INTO CDC_INBOX_MODULE_CONFIG (AGGREGATE_TYPE, SP_NAME, ACTIVE)
    VALUES ('actualizacionAfiliadoType', 'USP_INBOX_PARTICIPE', 1)
""")
print("  ok -> actualizacionAfiliadoType -> USP_INBOX_PARTICIPE")

orcl.commit()

# 6) Reprocesar eventos pending de este aggregate_type
print("\n[6] Reprocesar eventos pending de actualizacionAfiliadoType")
c.execute("""SELECT ID, AGGREGATE_TYPE, EVENT_TYPE, PAYLOAD FROM CDC_INBOX
             WHERE PROCESSED = 0 AND AGGREGATE_TYPE = 'actualizacionAfiliadoType'""")
rows = c.fetchall()
print(f"  pendientes: {len(rows)}")
processed = 0
for r in rows:
    try:
        c.execute("BEGIN USP_INBOX_PARTICIPE(:1, :2, :3); END;",
                  [r[1], r[2], r[3].read() if hasattr(r[3],'read') else r[3]])
        c.execute("UPDATE CDC_INBOX SET PROCESSED=1, PROCESSED_AT=SYSTIMESTAMP WHERE ID=:1", [r[0]])
        processed += 1
    except Exception as e:
        print(f"    err id={r[0]}: {str(e)[:150]}")
orcl.commit()
print(f"  procesados: {processed}")

# 7) Verificar datos en ACTUALIZACION_AFILIADO_TYPE
c.execute("SELECT COUNT(*) FROM ACTUALIZACION_AFILIADO_TYPE")
print(f"\n  ACTUALIZACION_AFILIADO_TYPE: {c.fetchone()[0]} filas")
c.execute("SELECT * FROM (SELECT CODIGO_CEDU, CODIGO_PROV, DESCRIPCION_CALL_PRIM FROM ACTUALIZACION_AFILIADO_TYPE ORDER BY CODIGO_CEDU) WHERE ROWNUM<=5")
for r in c.fetchall(): print(f"    {r}")
