import oracledb
o=oracledb.connect(user='fcme_user',password='FcmeUser2025!',dsn='10.35.3.223:31521/XEPDB1')
c=o.cursor()
ddl = r"""CREATE OR REPLACE PROCEDURE FCME_USER.USP_INBOX_JURIDICOINFOBASICA(
    p_id IN NUMBER, p_aggregate_type IN VARCHAR2, p_source_table IN VARCHAR2,
    p_event_type IN VARCHAR2, p_payload IN CLOB
) AS
    v_id VARCHAR2(50);
BEGIN
    SYS.DBMS_APPLICATION_INFO.SET_CLIENT_INFO('is_replicating');
    v_id := JSON_VALUE(p_payload,'$.co_juri');
    IF p_event_type IN ('DELETE','DELETED') THEN
        DELETE FROM FCME_USER.JURIDICOINFORMACIONBASICATYPE WHERE IDENTIFICACION = v_id;
    ELSE
        MERGE INTO FCME_USER.JURIDICOINFORMACIONBASICATYPE t
        USING (SELECT v_id AS k FROM dual) s
           ON (t.IDENTIFICACION = s.k)
        WHEN MATCHED THEN UPDATE SET CODIGOTIPOIDENTIFICACION = 'J'
        WHEN NOT MATCHED THEN INSERT (ID, IDENTIFICACION, CODIGOTIPOIDENTIFICACION)
            VALUES (FCME_USER.SEQ_JURIDICOINFORMACIONBASICATYPE_ID.NEXTVAL, v_id, 'J');
    END IF;
    SYS.DBMS_APPLICATION_INFO.SET_CLIENT_INFO('');
EXCEPTION WHEN OTHERS THEN
    SYS.DBMS_APPLICATION_INFO.SET_CLIENT_INFO('');
    INSERT INTO FCME_USER.CDC_INBOX_ERRORS(INBOX_ID,AGGREGATE_TYPE,EVENT_TYPE,ERROR_MESSAGE)
    VALUES (p_id,p_aggregate_type,p_event_type,'wrapper juridicoInfoBasica: '||SUBSTR(SQLERRM,1,500));
END;"""
c.execute(ddl)
o.commit()
print("OK USP_INBOX_JURIDICOINFOBASICA fixed")
o.close()
